#!/usr/bin/env python3
"""Generate include/miniOS/drivers/gop_font.h from a PSF2 8x16 font file."""
import gzip, struct, sys, os

def parse_unicode_table(data, hdr_sz, n_glyphs, bpg):
    """Return sorted list of (codepoint, glyph_index) pairs from PSF2 Unicode table."""
    ut_off = hdr_sz + n_glyphs * bpg
    cp_to_glyph = {}
    gi = 0
    pos = ut_off
    while pos < len(data) and gi < n_glyphs:
        while pos < len(data) and data[pos] != 0xFF:
            if data[pos] == 0xFE:
                pos += 1
                continue
            b = data[pos]
            if b < 0x80:
                cp = b; pos += 1
            elif b < 0xE0:
                cp = ((b & 0x1F) << 6) | (data[pos+1] & 0x3F); pos += 2
            elif b < 0xF0:
                cp = ((b & 0x0F) << 12) | ((data[pos+1] & 0x3F) << 6) | (data[pos+2] & 0x3F); pos += 3
            else:
                cp = ((b & 0x07) << 18) | ((data[pos+1] & 0x3F) << 12) | ((data[pos+2] & 0x3F) << 6) | (data[pos+3] & 0x3F); pos += 4
            if cp not in cp_to_glyph and cp <= 0xFFFF:
                cp_to_glyph[cp] = gi
        pos += 1
        gi += 1
    return sorted(cp_to_glyph.items())

def main():
    src  = sys.argv[1] if len(sys.argv) > 1 else '/usr/share/kbd/consolefonts/LatArCyrHeb-16.psfu.gz'
    dest = sys.argv[2] if len(sys.argv) > 2 else 'include/miniOS/drivers/gop_font.h'

    opener = gzip.open if src.endswith('.gz') else open
    data = opener(src, 'rb').read()

    magic = struct.unpack_from('<I', data, 0)[0]
    if magic != 0x864ab572:
        sys.exit(f'Not a PSF2 font: magic=0x{magic:08x}')

    _, hdr_sz, flags, n_glyphs, bpg, h, w = struct.unpack_from('<IIIIIII', data, 4)
    if w != 8 or h != 16 or bpg != 16:
        sys.exit(f'Expected 8x16 font with 16 bytes/glyph, got {w}x{h} bpg={bpg}')

    glyphs = []
    off = hdr_sz
    for _ in range(n_glyphs):
        glyphs.append(data[off:off + bpg])
        off += bpg

    has_unicode = bool(flags & 1)
    cp_map = parse_unicode_table(data, hdr_sz, n_glyphs, bpg) if has_unicode else []

    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, 'w') as f:
        f.write('/* Auto-generated by scripts/gen_font.py - do not edit.\n')
        f.write(' * Source: ' + os.path.basename(src) + '\n')
        f.write(f' * {n_glyphs} glyphs, 8x16 pixels, 1 byte per row (MSB = leftmost pixel).\n')
        if cp_map:
            f.write(f' * {len(cp_map)} Unicode codepoints in gop_cp_map[] (sorted, binary-searchable). */\n')
        else:
            f.write(' */\n')
        f.write('#ifndef _MINIOS_DRIVERS_GOP_FONT_H_\n')
        f.write('#define _MINIOS_DRIVERS_GOP_FONT_H_\n\n')
        f.write('#include <miniOS/types.h>\n\n')
        f.write(f'#define GOP_N_GLYPHS {n_glyphs}u\n')
        f.write('#define GOP_FONT_W   8\n')
        f.write('#define GOP_FONT_H   16\n\n')
        f.write(f'static const uint8_t vga_font_8x16[GOP_N_GLYPHS][GOP_FONT_H] = {{\n')
        for i, g in enumerate(glyphs):
            row = ', '.join(f'0x{b:02X}' for b in g)
            f.write(f'    /* {i:3d} */ {{ {row} }},\n')
        f.write('};\n\n')
        if cp_map:
            f.write(f'#define GOP_CP_MAP_SIZE {len(cp_map)}u\n\n')
            f.write('typedef struct { uint16_t cp; uint16_t glyph; } gop_cp_entry_t;\n\n')
            f.write(f'static const gop_cp_entry_t gop_cp_map[GOP_CP_MAP_SIZE] = {{\n')
            for cp, gi in cp_map:
                f.write(f'    {{ 0x{cp:04X}, {gi:3d} }},\n')
            f.write('};\n\n')
        f.write('#endif /* _MINIOS_DRIVERS_GOP_FONT_H_ */\n')

    print(f'Generated {dest} ({n_glyphs} glyphs, {len(cp_map)} Unicode mappings)')

if __name__ == '__main__':
    main()
